// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountStatus string

const (
	AccountStatusActive        AccountStatus = "active"
	AccountStatusPendingReview AccountStatus = "pending_review"
	AccountStatusSuspended     AccountStatus = "suspended"
	AccountStatusDeleted       AccountStatus = "deleted"
)

func (e *AccountStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountStatus(s)
	case string:
		*e = AccountStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountStatus: %T", src)
	}
	return nil
}

type NullAccountStatus struct {
	AccountStatus AccountStatus `json:"account_status"`
	Valid         bool          `json:"valid"` // Valid is true if AccountStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AccountStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountStatus), nil
}

type Account struct {
	ID             pgtype.UUID        `json:"id"`
	Phone          string             `json:"phone"`
	Status         AccountStatus      `json:"status"`
	TokenValidFrom pgtype.Timestamptz `json:"token_valid_from"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Address struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Country   string             `json:"country"`
	Region    pgtype.Text        `json:"region"`
	City      pgtype.Text        `json:"city"`
	Zone      pgtype.Text        `json:"zone"`
	Wereda    pgtype.Text        `json:"wereda"`
	Kebele    pgtype.Text        `json:"kebele"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID                pgtype.UUID        `json:"id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	FirstName         string             `json:"first_name"`
	MiddleName        pgtype.Text        `json:"middle_name"`
	LastName          string             `json:"last_name"`
	AliasName         pgtype.Text        `json:"alias_name"`
	Birthdate         pgtype.Date        `json:"birthdate"`
	Gender            pgtype.Text        `json:"gender"`
	Citizenship       pgtype.Text        `json:"citizenship"`
	Email             pgtype.Text        `json:"email"`
	UserHeadShotImage pgtype.Text        `json:"user_head_shot_image"`
	GovernmentIDImage pgtype.Text        `json:"government_id_image"`
	PassportImage     pgtype.Text        `json:"passport_image"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
