// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountByPhone = `-- name: GetAccountByPhone :one
SELECT id, phone, status, token_valid_from, created_at, updated_at FROM accounts
WHERE phone = $1 LIMIT 1
`

func (q *Queries) GetAccountByPhone(ctx context.Context, phone string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPhone, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Status,
		&i.TokenValidFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts 
SET status = $2, updated_at = CURRENT_TIMESTAMP 
WHERE id = $1
`

type UpdateAccountStatusParams struct {
	ID     pgtype.UUID   `json:"id"`
	Status AccountStatus `json:"status"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.ID, arg.Status)
	return err
}

const upsertAccount = `-- name: UpsertAccount :one


INSERT INTO accounts (phone)
VALUES ($1)
ON CONFLICT (phone) DO UPDATE 
SET updated_at = CURRENT_TIMESTAMP
RETURNING id, phone, status, token_valid_from, created_at, updated_at
`

// ****ACCOUNTS****
func (q *Queries) UpsertAccount(ctx context.Context, phone string) (Account, error) {
	row := q.db.QueryRow(ctx, upsertAccount, phone)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Status,
		&i.TokenValidFrom,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
