// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"
)

type Querier interface {
	GetAccountByPhone(ctx context.Context, phone string) (Account, error)
	UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error
	//****ACCOUNTS****
	UpsertAccount(ctx context.Context, phone string) (Account, error)
}

var _ Querier = (*Queries)(nil)
